// Generated by gencpp from file im_msgs/SetRGBRequest.msg
// DO NOT EDIT!


#ifndef IM_MSGS_MESSAGE_SETRGBREQUEST_H
#define IM_MSGS_MESSAGE_SETRGBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_msgs
{
template <class ContainerAllocator>
struct SetRGBRequest_
{
  typedef SetRGBRequest_<ContainerAllocator> Type;

  SetRGBRequest_()
    : mode(0)
    , frequency(0.0)
    , times(0)
    , color(0)  {
    }
  SetRGBRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , frequency(0.0)
    , times(0)
    , color(0)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;

   typedef float _frequency_type;
  _frequency_type frequency;

   typedef int8_t _times_type;
  _times_type times;

   typedef int8_t _color_type;
  _color_type color;


    enum { LEDOFF = 0 };
     enum { RED = 1 };
     enum { GREEN = 2 };
     enum { YELLOW = 3 };
     enum { BLUE = 4 };
     enum { PINK = 5 };
     enum { TURQUOISE = 6 };
     enum { WHITE = 7 };
     enum { MANUAL = 0 };
     enum { ON = 1 };
     enum { AUTONOMOUS = 2 };
     enum { TELEOP = 3 };
     enum { WANDER = 4 };
     enum { LOW_BATTERY = 5 };
     enum { CHARGING = 6 };
     enum { CHARGED = 7 };
     enum { ERROR = 8 };
 

  typedef boost::shared_ptr< ::im_msgs::SetRGBRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_msgs::SetRGBRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRGBRequest_

typedef ::im_msgs::SetRGBRequest_<std::allocator<void> > SetRGBRequest;

typedef boost::shared_ptr< ::im_msgs::SetRGBRequest > SetRGBRequestPtr;
typedef boost::shared_ptr< ::im_msgs::SetRGBRequest const> SetRGBRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_msgs::SetRGBRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_msgs::SetRGBRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'im_msgs': ['/home/zhang/catkin_ws/src/im_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_msgs::SetRGBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_msgs::SetRGBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_msgs::SetRGBRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "661adc9cdaa83965483792df034da13d";
  }

  static const char* value(const ::im_msgs::SetRGBRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x661adc9cdaa83965ULL;
  static const uint64_t static_value2 = 0x483792df034da13dULL;
};

template<class ContainerAllocator>
struct DataType< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_msgs/SetRGBRequest";
  }

  static const char* value(const ::im_msgs::SetRGBRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int8 LEDOFF    = 0\n\
int8 RED       = 1\n\
int8 GREEN     = 2\n\
int8 YELLOW    = 3\n\
int8 BLUE      = 4\n\
int8 PINK      = 5\n\
int8 TURQUOISE = 6\n\
int8 WHITE     = 7\n\
\n\
\n\
int8 MANUAL      = 0\n\
int8 ON          = 1\n\
int8 AUTONOMOUS  = 2\n\
int8 TELEOP      = 3\n\
int8 WANDER      = 4\n\
int8 LOW_BATTERY = 5\n\
int8 CHARGING    = 6\n\
int8 CHARGED     = 7\n\
int8 ERROR       = 8\n\
\n\
int8 mode\n\
\n\
float32 frequency\n\
\n\
int8 times\n\
int8 color\n\
";
  }

  static const char* value(const ::im_msgs::SetRGBRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.frequency);
      stream.next(m.times);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRGBRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_msgs::SetRGBRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_msgs::SetRGBRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "frequency: ";
    Printer<float>::stream(s, indent + "  ", v.frequency);
    s << indent << "times: ";
    Printer<int8_t>::stream(s, indent + "  ", v.times);
    s << indent << "color: ";
    Printer<int8_t>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_MSGS_MESSAGE_SETRGBREQUEST_H
