// Generated by gencpp from file im_msgs/SetRGB.msg
// DO NOT EDIT!


#ifndef IM_MSGS_MESSAGE_SETRGB_H
#define IM_MSGS_MESSAGE_SETRGB_H

#include <ros/service_traits.h>


#include <im_msgs/SetRGBRequest.h>
#include <im_msgs/SetRGBResponse.h>


namespace im_msgs
{

struct SetRGB
{

typedef SetRGBRequest Request;
typedef SetRGBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRGB
} // namespace im_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_msgs::SetRGB > {
  static const char* value()
  {
    return "09e0749c01af9e427f1a861c70df57ff";
  }

  static const char* value(const ::im_msgs::SetRGB&) { return value(); }
};

template<>
struct DataType< ::im_msgs::SetRGB > {
  static const char* value()
  {
    return "im_msgs/SetRGB";
  }

  static const char* value(const ::im_msgs::SetRGB&) { return value(); }
};


// service_traits::MD5Sum< ::im_msgs::SetRGBRequest> should match 
// service_traits::MD5Sum< ::im_msgs::SetRGB > 
template<>
struct MD5Sum< ::im_msgs::SetRGBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_msgs::SetRGB >::value();
  }
  static const char* value(const ::im_msgs::SetRGBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_msgs::SetRGBRequest> should match 
// service_traits::DataType< ::im_msgs::SetRGB > 
template<>
struct DataType< ::im_msgs::SetRGBRequest>
{
  static const char* value()
  {
    return DataType< ::im_msgs::SetRGB >::value();
  }
  static const char* value(const ::im_msgs::SetRGBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_msgs::SetRGBResponse> should match 
// service_traits::MD5Sum< ::im_msgs::SetRGB > 
template<>
struct MD5Sum< ::im_msgs::SetRGBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_msgs::SetRGB >::value();
  }
  static const char* value(const ::im_msgs::SetRGBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_msgs::SetRGBResponse> should match 
// service_traits::DataType< ::im_msgs::SetRGB > 
template<>
struct DataType< ::im_msgs::SetRGBResponse>
{
  static const char* value()
  {
    return DataType< ::im_msgs::SetRGB >::value();
  }
  static const char* value(const ::im_msgs::SetRGBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_MSGS_MESSAGE_SETRGB_H
